name: Node.js CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install docker-compose
      run: sudo apt-get install -y docker-compose

    - name: Install dependencies
      run: npm install

    - name: .env setup
      run: cp .env.test .env

    - name: Database migration
      run: npm run migrate

    - name: Run tests
      run: npm run test
